2022-01-20:13:20:04,97 INFO     [app.py:15] Starting app
2022-01-20:13:20:04,97 INFO     [app.py:19] Connecting to database
2022-01-20:13:20:04,347 INFO     [app.py:25] Connected to database
2022-01-20:13:20:04,378 INFO     [_internal.py:225]  * Restarting with stat
2022-01-20:13:20:04,831 INFO     [app.py:15] Starting app
2022-01-20:13:20:04,831 INFO     [app.py:19] Connecting to database
2022-01-20:13:20:04,909 INFO     [app.py:25] Connected to database
2022-01-20:13:20:04,925 WARNING  [_internal.py:225]  * Debugger is active!
2022-01-20:13:20:04,925 INFO     [_internal.py:225]  * Debugger PIN: 552-907-874
2022-01-20:13:20:04,956 INFO     [_internal.py:225]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-01-20:13:20:48,407 INFO     [app.py:38] {'name': 'prabal', 'username': '58prabal'}
2022-01-20:13:20:48,595 INFO     [app.py:52] Successully saved data
2022-01-20:13:20:48,595 INFO     [_internal.py:225] 127.0.0.1 - - [20/Jan/2022 13:20:48] "POST / HTTP/1.1" 200 -
